<a href="https://colab.research.google.com/github/jewel-pruthi/python-numpy_practice/blob/main/Basic_array_operations_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The objective of this colab notebook is to demonstrate basics of numpy arrays, incl. but not limited to the following operations:**



*   Array creation
*   Properties like dimensions, shape of array etc.
*   Array of Zeros and Ones, sequenced values
*   Unary and binary matrix operations
*   Indexing and slicing
*   Array manipulation like flattening, modifying dimensions, stacking, creating a copy etc.


In [1]:
# Importing the numpy library
import numpy as np

In [2]:
# Create an array. Enclose every new dimension in a []

arr_1d = np.array([1,2,3])
print('1d array example : \n',arr_1d)

arr_2d = np.array([[1.,2.,3.],
                   [4.,5.,6.]])
print('\n2d array example : \n', arr_2d)

arr_3d = np.array([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]
                    ],
                   [[13,14,15,16],
                    [17,18,19,20],
                    [21,22,23,24]
                    ]])
print('\n3d array example : \n', arr_3d)

1d array example : 
 [1 2 3]

2d array example : 
 [[1. 2. 3.]
 [4. 5. 6.]]

3d array example : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [3]:
# Find the dimension (or axes) of array. Simply put, this is the length of the shape tuple.

print('Dimensions in 1d array: ',arr_1d.ndim)
print('\nDimensions in 2d array: ',arr_2d.ndim)
print('\nDimensions in 3d array: ', arr_3d.ndim)


Dimensions in 1d array:  1

Dimensions in 2d array:  2

Dimensions in 3d array:  3


In [4]:
# Find shape of array i.e. number of dimensions

print('Shape of 1d array:', arr_1d.shape)
print('\nShape of 2d array:', arr_2d.shape)
print('\nShape of 3d array:',arr_3d.shape)


Shape of 1d array: (3,)

Shape of 2d array: (2, 3)

Shape of 3d array: (2, 3, 4)


In [5]:
# Find out data type of array

print('Datatype of 1d array : ', arr_1d.dtype)
print('Datatype of 2d array : ', arr_2d.dtype)

Datatype of 1d array :  int64
Datatype of 2d array :  float64


In [6]:
# Create an array of zeros and ones

arr_1d_zeros = np.zeros((3,))
arr_2d_zeros = np.zeros((3,3))
arr_3d_zeros = np.zeros((2,3,4))

print('1d zeros array : \n', arr_1d_zeros)
print('\n2d zeros array : \n', arr_2d_zeros)
print('\n3d zeros array : \n', arr_3d_zeros)

#Similarly use np.ones((placeholder for tuple of array size)) to create an array of ones

arr_2d_ones = np.ones((3,4))
print('\n2d ones array : \n',arr_2d_ones)

1d zeros array : 
 [0. 0. 0.]

2d zeros array : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3d zeros array : 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

2d ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# To create arrays with sequence of numbers, one can use either arange or linspace functions
# np.arange(start, stop, stepsize) --> becomes tricky to use with floating point stepsize as
#  there is no guarantee of the number of elements returned due to floating precision
# np.linspace(start, stop, number of elements ) 

arr_seq = np.arange(0,12,1).reshape(3,4)
print('2d array sequence from 0-11 : \n', arr_seq)

float_arr_seq = np.arange(0,2,0.3) #using reshape here will throw an error
print('\nFloating point sequenced array : \n', float_arr_seq)

float_arr = np.linspace(0,2,8).reshape(2,4)
print('\n Floating point fixed dimension array : \n', float_arr)

2d array sequence from 0-11 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Floating point sequenced array : 
 [0.  0.3 0.6 0.9 1.2 1.5 1.8]

 Floating point fixed dimension array : 
 [[0.         0.28571429 0.57142857 0.85714286]
 [1.14285714 1.42857143 1.71428571 2.        ]]


In [8]:
# Element-wise array operations

A = np.linspace(1,4,4).reshape(2,2)
B = np.linspace(5,8,4).reshape(2,2)
print('A :\n',A)
print('\nB:\n',B)

print('\n A+B : \n', A+B)
print('\n A+B using add fn : \n', np.add(A,B))
print('\n A-B : \n', A-B)
print('\n A-B using subtract fn : \n', np.subtract(A,B))
print('\n A*B : \n', A*B)
print('\n Dot product (matrix multiplication): \n', A.dot(B))
print('\n Dot product (matrix multiplication): \n', A@B)



A :
 [[1. 2.]
 [3. 4.]]

B:
 [[5. 6.]
 [7. 8.]]

 A+B : 
 [[ 6.  8.]
 [10. 12.]]

 A+B using add fn : 
 [[ 6.  8.]
 [10. 12.]]

 A-B : 
 [[-4. -4.]
 [-4. -4.]]

 A-B using subtract fn : 
 [[-4. -4.]
 [-4. -4.]]

 A*B : 
 [[ 5. 12.]
 [21. 32.]]

 Dot product (matrix multiplication): 
 [[19. 22.]
 [43. 50.]]

 Dot product (matrix multiplication): 
 [[19. 22.]
 [43. 50.]]


In [9]:
# Unary matrix operations

print('A : \n',A)
print('\nUnary sum of A : ',  A.sum())
print('Minimum element in A : ', A.min())
print('Maximum element in A : ', A.max())
print('Mean of elements in A : ', A.mean())

print('\nSum of A along rows : ', A.sum(axis = 0))
print('\nSum of A along columns : ', A.sum(axis = 1))
print('\nCumulative sum of A (flattened): \n', np.cumsum(A))
print('\nCumulative sum of A (along columns): \n', np.cumsum(A, axis = 1))


A : 
 [[1. 2.]
 [3. 4.]]

Unary sum of A :  10.0
Minimum element in A :  1.0
Maximum element in A :  4.0
Mean of elements in A :  2.5

Sum of A along rows :  [4. 6.]

Sum of A along columns :  [3. 7.]

Cumulative sum of A (flattened): 
 [ 1.  3.  6. 10.]

Cumulative sum of A (along columns): 
 [[1. 3.]
 [3. 7.]]


In [10]:
# Universal functions --> np.sin(), np.cos(), np.exp()

print('A : \n', A)
print('\nsin(A) : \n',np.sin(A))
print('\ncos(A) : \n',np.cos(A))
print('\nexp(A) : \n', np.exp(A))
print('\nSqrt of A : \n', np.sqrt(A))

A : 
 [[1. 2.]
 [3. 4.]]

sin(A) : 
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos(A) : 
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

exp(A) : 
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

Sqrt of A : 
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
# Short-hand notations for matrix operations

print('A : \n', A)
print('B : \n', B)

A+=B
print('\nUpdated A with A+B : \n', A)

A-=B
print('\nUpdated A with A-B : \n', A)

A*=B
print('\nUpdated A with A*B : \n', A)

A/=B
print('\nUpdated A with A/B : \n', A)

A : 
 [[1. 2.]
 [3. 4.]]
B : 
 [[5. 6.]
 [7. 8.]]

Updated A with A+B : 
 [[ 6.  8.]
 [10. 12.]]

Updated A with A-B : 
 [[1. 2.]
 [3. 4.]]

Updated A with A*B : 
 [[ 5. 12.]
 [21. 32.]]

Updated A with A/B : 
 [[1. 2.]
 [3. 4.]]


In [40]:
# Indexing and slicing operations (each axes has a unique index)
# 1d array --> arr_1d[start : stop : stepsize]
# 2d array --> arr[tuple of inddex ranges for both axes], eg. arr_2d[start:stop:step, start:stop:step]
# n-dimensional arrays --> specify the index range for the desired axes and rest can be skipped
#  through ... (3 dots) , eg.,
#  for an array with 5 dimensions arr_5d[0:3,...] equivalesnt to arr_5d[0:3,:,:,:,:]

print('1d array : ',arr_1d)
print('First two elements : ', arr_1d[0:2:])

array_2d = np.arange(24).reshape(4,6)
print('\n 2d array : \n', array_2d)
print('\n Displaying 3rd column even indices', array_2d[0::2,2])

array_5d = np.linspace(0,1000,72, dtype = np.int32).reshape(2,3,1,4,3)
print('\n 5d array : \n', array_5d)
print('\nDisplaying first 3 rows of 4th dimension in the 5d array : \n\n', array_5d[...,0:3,:])



1d array :  [1 2 3]
First two elements :  [1 2]

 2d array : 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 Displaying 3rd column even indices [ 2 14]

 5d array : 
 [[[[[   0   14   28]
    [  42   56   70]
    [  84   98  112]
    [ 126  140  154]]]


  [[[ 169  183  197]
    [ 211  225  239]
    [ 253  267  281]
    [ 295  309  323]]]


  [[[ 338  352  366]
    [ 380  394  408]
    [ 422  436  450]
    [ 464  478  492]]]]



 [[[[ 507  521  535]
    [ 549  563  577]
    [ 591  605  619]
    [ 633  647  661]]]


  [[[ 676  690  704]
    [ 718  732  746]
    [ 760  774  788]
    [ 802  816  830]]]


  [[[ 845  859  873]
    [ 887  901  915]
    [ 929  943  957]
    [ 971  985 1000]]]]]

Displaying first 3 rows of 4th dimension in the 5d array : 

 [[[[[  0  14  28]
    [ 42  56  70]
    [ 84  98 112]]]


  [[[169 183 197]
    [211 225 239]
    [253 267 281]]]


  [[[338 352 366]
    [380 394 408]
    [422 436 450]]]]



 [[[[507 521 535]
    [

In [41]:
# Array dimension manipulations

# Flattening an n-dimensional array to 1d list
print('2d array : \n ', array_2d)
print('\nFlattened array : ', array_2d.ravel())

# Reshaping the array through reshape()
# reshape() returns its array argument with the new size but doesn't modify the original array
# Syntax : array_reference.reshape(new_size_tuple)
print('\n5d array :\n', array_5d)
print('\nExample of 5d array reshaped to 2d : \n', array_5d.reshape((8,9)))

# Reshaping the array through resize()
# resize() modifies the array in-place into the new dimensions
# Syntax : array_reference.resize(new_tuple_size)

print('\n5d array after applying reshape fn :\n', array_5d) #Same as original dimensions of array_5d
array_5d.resize(8,9)
print('\nExample of updated 5d array to 2d : \n', array_5d)


2d array : 
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

5d array :
 [[[[[   0   14   28]
    [  42   56   70]
    [  84   98  112]
    [ 126  140  154]]]


  [[[ 169  183  197]
    [ 211  225  239]
    [ 253  267  281]
    [ 295  309  323]]]


  [[[ 338  352  366]
    [ 380  394  408]
    [ 422  436  450]
    [ 464  478  492]]]]



 [[[[ 507  521  535]
    [ 549  563  577]
    [ 591  605  619]
    [ 633  647  661]]]


  [[[ 676  690  704]
    [ 718  732  746]
    [ 760  774  788]
    [ 802  816  830]]]


  [[[ 845  859  873]
    [ 887  901  915]
    [ 929  943  957]
    [ 971  985 1000]]]]]

Example of 5d array reshaped to 2d : 
 [[   0   14   28   42   56   70   84   98  112]
 [ 126  140  154  169  183  197  211  225  239]
 [ 253  267  281  295  309  323  338  352  366]
 [ 380  394  408  422  436  450  464  478  492]
 [ 507  521  535  549  563  577 

In [50]:
# Stacking multiple arrays together
# Vertical stack - Stacks one array over the another along the first dimension. The argumnents to 
# the function must have the same dimensions.
# Syntax : npvstack(tuple(array1, array2, ...))

# Horizontal stacking - Appends one array over the another along the second dimension. The arguments to the
# function must have the same dimensions.
# Syntax : np.hstack(tuple(array1, array2, ...))

a = np.linspace(0,24,24, dtype = np.int32).reshape(2,3,4)
b = np.linspace(25,100,24, dtype = np.int32).reshape(2,3,4)

print('Array A : \n', a)
print('\nArray B : \n', b)
print('\nArray B stacked along rows on array A : \n', np.vstack((a,b)))

print('\n Array B stacked along columns on array A : \n', np.hstack((a,b)))

Array A : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 24]]]

Array B : 
 [[[ 25  28  31  34]
  [ 38  41  44  47]
  [ 51  54  57  60]]

 [[ 64  67  70  73]
  [ 77  80  83  86]
  [ 90  93  96 100]]]

Array B stacked along rows on array A : 
 [[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  24]]

 [[ 25  28  31  34]
  [ 38  41  44  47]
  [ 51  54  57  60]]

 [[ 64  67  70  73]
  [ 77  80  83  86]
  [ 90  93  96 100]]]

 Array B stacked along columns on array A : 
 [[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [ 25  28  31  34]
  [ 38  41  44  47]
  [ 51  54  57  60]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  24]
  [ 64  67  70  73]
  [ 77  80  83  86]
  [ 90  93  96 100]]]


In [52]:
# Creating a copy of an array

a = np.arange(4).reshape(2,2)
print('Array a :\n ', a)
copy_a = np.copy(a)
print('\nCopy of array A : \n', copy_a)
print('\nDoes array A and its copy have the same memory reference? ', copy_a is a)

Array a :
  [[0 1]
 [2 3]]

Copy of array A : 
 [[0 1]
 [2 3]]

Does array A and its copy have the same memory reference?  False


In [55]:
# Transpose of an array

original_array = np.linspace(1,100,10, dtype = np.int32).reshape(2,5)
print('Original array ', original_array.shape, ': \n', original_array)
print('\nTransposed array ', original_array.T.shape, ': \n', original_array.T)

Original array  (2, 5) : 
 [[  1  12  23  34  45]
 [ 56  67  78  89 100]]

Transposed array  (5, 2) : 
 [[  1  56]
 [ 12  67]
 [ 23  78]
 [ 34  89]
 [ 45 100]]
